#@package _global_

# define and configure the dataset class which is called by hydra
#dataset:
#  _target_: datasets.Cityscapes.Cityscapes.Cityscapes_dataset
#  root:     ${paths.Cityscapes}
dataset:
  _target_: datasets.Base_Datasets.base.Base_Dataset
  root:     ${paths.Cityscapes}
  img_folder: "leftImg8bit_trainvaltest/leftImg8bit/train/*/"
  img_folder_val: "leftImg8bit_trainvaltest/leftImg8bit/val/*/"
  label_folder: "gtFine_trainvaltest/gtFine/train/*/"
  label_folder_val: "gtFine_trainvaltest/gtFine/val/*/"
  label_postfix: "labelIds_19classes"

# additional information about the dataset
DATASET:
  ##NEEDED PARAMETERS
  NAME:         "Cityscapes"
  NUM_CLASSES:  19
  IGNORE_INDEX: 255
  #INFORMATION ABOUT DS, NOT NEEDED
  SIZE:
    TRAIN: 2975
    VAL:   500
    TEST:  1525
  #NEEDED IF WEIGHTED LOSSFUNCTIONS ARE USED
  CLASS_WEIGHTS: [ 0.8373, 0.918, 0.866, 1.0345,1.0166, 0.9969, 0.9754, 1.0489, 0.8786, 1.0023, 0.9539, 0.9843, 1.1116, 0.9037, 1.0865, 1.0955, 1.0865, 1.1529, 1.0507 ]
  #OPTIONAL - JUST IF CLASS LOGGING RESULTS ARE WANTED
  CLASS_LABELS:
    - road
    - sidewalk
    - building
    - wall
    - fence
    - pole
    - traffic light
    - traffic sign
    - vegetation
    - terrain
    - sky
    - person
    - rider
    - car
    - truck
    - bus
    - train
    - motorcycle
    - bicycle
