dataset:
  _target_: src.datasets.base_datasets.cross_validation_sampling.CVSamplingDataset    # Path to the Dataset File
  root: ${paths.Cityscapes}                                         # Root to the data
  img_folder: "leftImg8bit_trainvaltest/leftImg8bit/train/*/"       # Folder to the images for training
  img_folder_test: "leftImg8bit_trainvaltest/leftImg8bit/val/*/"    # Folder to the images for validation
  label_folder: "gtFine_trainvaltest/gtFine/train/*/"               # Folder to the labels for training
  label_folder_test: "gtFine_trainvaltest/gtFine/val/*/"            # Folder to the labels for validation
  label_postfix: "labelIds_19classes"                               # Postfix of the label files
  dtype: ".png"                                                     # Data type of the image files
  dtype_mask: ".png"                                                # Data type of the label files
  fold: ${fold}                                                     # Fold which should be used for training
  num_classes: ${dataset.num_classes}                               # Number of Classes
  batch_size: ${batch_size}                                         # Batch size, needed for computing the number of steps
  patch_size: ${augmentation.cfg.crop_size}                         # Patch size which should be used for patching
  scale_limit: ${augmentation.cfg.scale_limit}                      # Scale limit for scaling the patches

name: Cityscapes_CV             # Name of the dataset, needed for logging
num_classes: 19                 # Number of classes in the dataset
ignore_index: 255               # Ignore Index of the dataset (not required)
class_weights: [ 0.8373, 0.918, 0.866, 1.0345,1.0166, 0.9969, 0.9754, 1.0489, 0.8786, 1.0023, 0.9539, 0.9843, 1.1116, 0.9037, 1.0865, 1.0955, 1.0865, 1.1529, 1.0507 ]          # weights of classes, when using weighted loss functions (not required)
segmentation_type: semantic     # Typ of segmentation, one of - semantic, instance or multilabel
class_labels:                   # Name for each class
  - road
  - sidewalk
  - building
  - wall
  - fence
  - pole
  - traffic light
  - traffic sign
  - vegetation
  - terrain
  - sky
  - person
  - rider
  - car
  - truck
  - bus
  - train
  - motorcycle
  - bicycle