#@package _global_
# afterwards you can handle your custom input arguments which are used to initialize the dataset
dataset:
  _target_: datasets.Fishinspector.Fishinspector.Fishinspector_dataset
  root: ${paths.Fishinspector}               #the root if defined in config/environment/used_env.yaml
  img_folder: imagesTr
  label_folder: labelsTr
  fold: 0
  num_classes: ${DATASET.NUM_CLASSES}
  batch_size: ${batch_size}

# DATASET is used to store information about the dataset which are needed during training
DATASET:
  max_size: (345,1024)
  min_size: (190,776)
  NAME: Fishinspector
  NUM_CLASSES: 16
  CLASS_LABELS:
    - contour_LAT # 0
    - yolk_DV # 1
    - mouth_tip_LAT # 2
    - eye_LAT # 3
    - pericard_LAT #4
    - eye1_DV # 5
    - contour_DV # 6
    - fin1_DV # 7
    - otolith1_LAT # 8
    - otolith2_LAT # 9
    - eye2_DV # 10
    - notochord_LAT # 11
    - swimbladder_LAT # 12
    - yolk_LAT # 13
    - fin2_DV # 14
    - pigmentation_LAT # 15