dataset:
  _target_: src.datasets.fishinspector.fishinspector_partly_labeled.FishinspectorDatasetPL
  root: ${paths.Fishinspector}
  img_folder: imagesTr
  img_folder_test: imagesTr
  label_folder: labelsTr
  label_folder_test: labelsTr
  #img_folder_test: ../AIR_video_first_frame_lateral
  fold: ${fold}
  num_classes: ${dataset.num_classes}
  batch_size: ${batch_size}

name: Fishinspector_PL
num_classes: 16
segmentation_type: multilabel
class_labels:
  - contour_LAT       # 0
  - yolk_DV           # 1
  - mouth_tip_LAT     # 2
  - eye_LAT           # 3
  - pericard_LAT      # 4
  - eye1_DV           # 5
  - contour_DV        # 6
  - fin1_DV           # 7
  - otolith1_LAT      # 8
  - otolith2_LAT      # 9
  - eye2_DV           # 10
  - notochord_LAT     # 11
  - swimbladder_LAT   # 12
  - yolk_LAT          # 13
  - fin2_DV           # 14
  - pigmentation_LAT  # 15