_target_: src.datasets.base_datasets.base.BaseDataset
# Data Handling
root: ${dataset.root}
img_loader: ${img_loader}
label_handler: ${label_handler}
# Folder Structure
img_folder: ${dataset.img_folder}
label_folder: ${dataset.label_folder}
img_folder_val: ${dataset.img_folder_val}
label_folder_val: ${dataset.label_folder_val}
img_folder_test: ${dataset.img_folder_test}
label_folder_test: ${dataset.label_folder_test}