name: DeepLabv3
pretrained: True
model:
  _target_: src.models.DeepLabv3.get_seg_model #torchvision.models.segmentation.deeplabv3_resnet101
  num_classes: ${dataset.num_classes}
  pretrained: ${model.pretrained}
  aux_loss: True
  backbone: resnet101 #resnet50 or resnet101

