#@package _global_
model:
  _target_: models.FCN.get_seg_model
  num_classes: ${DATASET.NUM_CLASSES}
  pretrained: True
  aux_loss: True
  backbone: resnet101 #resnet50 or resnet101

MODEL:
  NAME: FCN