#@package _global_
model:
  _target_: models.FCN.get_seg_model #torchvision.models.segmentation.fcn_resnet101
  num_classes: ${DATASET.NUM_CLASSES}
  pretrained: True
  aux_loss: True
  backbone: resnet101 #resnet50 or resnet101

MODEL:
  NAME: FCN