name: FCN
pretrained: True
model:
  _target_: src.models.FCN.get_seg_model #torchvision.models.segmentation.fcn_resnet101
  num_classes: ${dataset.num_classes}
  pretrained: ${model.pretrained}
  aux_loss: True
  backbone: resnet101 #resnet50 or resnet101