# @package _global_
#CALLBACKS:
#  ms_restriction_callback:
#    _target_: utils.callbacks.MS_RestictionCallback
#    ms_offset: ${MODEL.MSCALE_OFFSET}
#    m_scale_training: ${MODEL.MSCALE_TRAINING}
#    epochs: ${epochs}
model:
  _target_: models.hrnet_ocr_ms.get_seg_model
  cfg:
    MODEL: ${MODEL}
    DATASET:
      NUM_CLASSES: ${DATASET.NUM_CLASSES}

TESTING:
  TEST_AFTERWARDS: True

MODEL:
  NAME: hrnet_ocr_ms
  #PRETRAINED_WEIGHTS: 'pretrained/hrnetv2_w48_imagenet_pretrained.pth'
  PRETRAINED_WEIGHTS: /pretrained/HRNet_W48_C_ssld_pretrained.pth
  #MSCALE_OFFSET: 0.75 #Offset, N_Scale are only used during Validation in the last 25% of training to speed up training time
  MSCALE_INFERENCE: False
  ALIGN_CORNERS: True
  MSCALE_LO_SCALE: 0.5
  SEGATTN_BOT_CH: 256
  N_SCALES: [0.5,1.0,2.0]
  MSCALE_DROPOUT: False
  MSCALE_INNER_3x3: True
  OCR:
    MID_CHANNELS: 512
    KEY_CHANNELS: 256
    DROPOUT: 0.05
    SCALE: 1
  EXTRA:
    FINAL_CONV_KERNEL: 1
    STAGE1:
      NUM_MODULES: 1
      NUM_RANCHES: 1
      BLOCK: BOTTLENECK
      NUM_BLOCKS:
      - 4
      NUM_CHANNELS:
      - 64
      FUSE_METHOD: SUM
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      - 384
      FUSE_METHOD: SUM

