name: SegNeXt
pretrained: True
model:
  _target_: src.models.mmseg_wrapper.get_model
  path: "src/models/mmseg_configs/SegNeXt_l.py"
  num_classes: ${dataset.num_classes}
  pretrained: ${model.pretrained}