name: SMP
pretrained: True
model:
  _target_: src.models.SMP.get_seg_model
  in_channels: 3
  num_classes: ${dataset.num_classes}
  pretrained: ${model.pretrained}
  backbone: tu-maxvit_base_tf_512
  # tu-tf_efficientnetv2_m.in21k
  # tu-tf_efficientnetv2_l.in21k
  # tu-tf_efficientnetv2_xl.in21k
  # tu-resnetv2_101x3_bit.goog_in21k more than 20GB
  arch: FPN

