# @package _global_
defaults:
- override data_augmentations: PASCALContext #default

batch_size: 8 #16
val_batch_size: ${batch_size}
epochs: 150 #400
optimizer: sgd
lr_scheduler: poly
lr: 0.001 #0.01 #LR: 0.01445439770745928
wd: 0.0001 #0.0005
momentum: 0.9
lossfunction: [ "wCE", "wCE", "wCE", "wCE"]
lossweight:   [1.0, 0.4, 0.05, 0.05]
