#@package _global_
#Hyperparameters for VOC2010 Context Dataset Dataset
batch_size: 8                   # batch size per gpu for training
val_batch_size: ${batch_size}   # batch size per gpu for validation
epochs: 200                     # number of eposchs
lr: 0.004                       # learning rate for training
momentum: 0.9                   # momentum for optimizer
weight_decay: 0.0001            # wd for optimizer
lossfunction: [ "CE", "CE", "CE", "CE"]         # list of lossfunctions
lossweight:   [1.0, 0.4, 0.05, 0.05]            # corresponding weights for each loss function
