#@package _global_
CALLBACKS:
  time_callback:
    _target_: utils.callbacks.TimeCallback
  lr_monitor:
    _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: 'step'
  tqdm_progressbar:
    _target_: pytorch_lightning.callbacks.progress.TQDMProgressBar
    refresh_rate: 100
  model_summary:
    _target_: pytorch_lightning.callbacks.ModelSummary
    max_depth: 2
  gpu_stats_monitor:
    _target_: pytorch_lightning.callbacks.GPUStatsMonitor
