#@package _global_
METRIC:
  NAME: Dice
  DURING_TRAIN: False
  METRIC_CALL: global
  METRICS:
    mIoU:
      _target_: utils.metric.Dice
      num_classes: ${DATASET.NUM_CLASSES}
      labels: ${DATASET.CLASS_LABELS}


