#@package _global_
METRIC:
  NAME: mIoU_stepwise
  DURING_TRAIN: False
  METRIC_CALL: stepwise
  METRICS:
    mIoU:
      _target_: utils.metric.IoU
      num_classes: ${DATASET.NUM_CLASSES}
      per_class: True
      ignore_class: 0
      labels: ${DATASET.LABELS}




