#@package _global_
METRIC:
  NAME: map          # which metric to optimize - mean Dice over the classes
  train_metric: False    # If also a train metric is wanted (in addition to a validation metric)
  call_global: True      # If True metric is updated in each step and computed once at the end of the epoch
  call_stepwise: False   # If True metric is computed in each step (usually one batch) and averaged over all steps - exclusively with call_per_img
  call_per_img: False    # If True metric is computed for each image and averaged over all images - exclusively with call_stepwise
  METRICS:
    MAP:             # Define the Metric
      _target_: torchmetrics.detection.mean_ap.MeanAveragePrecision    # Metric Classs
      #iou_type: segm