#@package _global_
METRIC:
  NAME: mIoU
  DURING_TRAIN: False
  METRIC_CALL: global
  METRICS:
    mIoU:
      _target_: utils.metric.IoU
      num_classes: ${DATASET.NUM_CLASSES}
      labels: ${DATASET.CLASS_LABELS}


