name: meanIoU                 # Name of the metric to optimize - is needed for logging and checkpointing
train_metric: False       # If also a train metric is wanted (in addition to a validation metric)
metric_per_img: False     # If True metric is computed for each image and averaged over all images
metric_global: True       # If True metric is updated in each step and computed once at the end of the epoch
metrics:
  meanIoU: # Define the Metric
    _target_: src.metric.iou.IoU     # Metric Class
    num_classes: ${dataset.num_classes}      # Number of Classes in the Dataset
    labels: ${dataset.class_labels}          # Class Labels in the Dataset
    per_class: False    # Return the mean Metric with or without the Metric for each Class