#@package _global_
AUGMENTATIONS:
  TRAIN:
    Resize:
        height: 512
        width: 1024
        p: 1.0
    Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    ToTensorV2:
  TEST:
    Normalize:
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    ToTensorV2: