#@package _global_
AUGMENTATIONS:
  TRAIN:
    RandomScale:
      scale_limit: [ -0.5,1.0 ]
      p: 1.0
    RandomCrop:
      height: 512
      width: 1024
    HorizontalFlip:
      p: 0.5
    Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    ToTensorV2:
  TEST:
    Normalize:
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    ToTensorV2: