#@package _global_
AUGMENTATIONS:
  TRAIN:
    Resize:
      height: 480 #512
      width: 480 #512
    HorizontalFlip:
      p: 0.5
    Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    ToTensorV2:
  TEST:
    Resize:
      height: 480
      width: 480
    Normalize:
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    ToTensorV2: