#@package _global_
AUGMENTATIONS:
  TRAIN:
    SmallestMaxSize:
      max_size: 520
    RandomScale:
      scale_limit: [ -0.5,1.0 ]
      p: 1.0
    PadIfNeeded:
      min_height: 520
      min_width: 520
      border_mode: 0 #"cv2.BORDER_CONSTANT"
      value: 0
      mask_value: ${DATASET.IGNORE_INDEX}
    RandomCrop:
      height: 520
      width: 520
    #Resize:
    #  height: 480 #512
    #  width: 480 #512
    HorizontalFlip:
      p: 0.5
    Normalize:
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    ToTensorV2:

  TEST:
    #Resize:
    #  height: 480 #512
    #  width: 480 #512
    PadIfNeeded:
      min_height: 500
      min_width: 500
      border_mode: 0 #"cv2.BORDER_CONSTANT"
      value: 0
      mask_value: ${DATASET.IGNORE_INDEX}
    Normalize:
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    ToTensorV2: