dataset:
  _target_: src.datasets.base_datasets.multilabel.MultilabelDataset     # Path to the Dataset File
  root: ${paths.dacl10k}                             # Root to the data
  img_folder: images_train                  # Folder to the images for training
  img_folder_val: images_val
  label_folder: labels_train               # Folder to the labels for training
  label_folder_val: labels_val
  dtype: ".jpg"                 # Data type of the image files
  dtype_mask: ".png"            # Data type of the label files
  num_classes: ${dataset.num_classes}             # Number of Classes

name: dacl10k                 # Name of the dataset, needed for logging
num_classes: 19                   # Number of classes in the dataset
segmentation_type: multilabel   # Typ of segmentation, one of - semantic, instance or multilabel
class_labels:                   # Name for each class
  - Crack
  - ACrack
  - Wetspot
  - Efflorescence
  - Rust
  - Rockpocket
  - Hollowareas
  - Cavity
  - Spalling
  - Graffiti
  - Weathering
  - Restformwork
  - ExposedRebars
  - Bearing
  - EJoint
  - Drainage
  - PEquipment
  - JTape
  - WConccor