dataset:
  _target_: src.datasets.base_datasets.multilabel.MultilabelSamplingCVDataset     # Path to the Dataset File
  root: ${paths.dacl10k}                             # Root to the data
  img_folder: images_*                  # Folder to the images for training
  label_folder: labels_*                # Folder to the labels for training
  dtype: ".jpg"                 # Data type of the image files
  dtype_mask: ".png"            # Data type of the label files
  fold: ${fold}                 # Fold which should be used for training
  num_classes: ${dataset.num_classes}             # Number of Classes
  batch_size: ${batch_size}     # Batch size, needed for computing the number of steps
  patch_size: ${augmentation.cfg.crop_size}       # Patch size which should be used for patching
  scale_limit: ${augmentation.cfg.scale_limit}    # Scale limit for scaling the patches


name: dacl10k                 # Name of the dataset, needed for logging
num_classes: 19                   # Number of classes in the dataset
segmentation_type: multilabel   # Typ of segmentation, one of - semantic, instance or multilabel
class_labels:                   # Name for each class
  - Crack
  - ACrack
  - Wetspot
  - Efflorescence
  - Rust
  - Rockpocket
  - Hollowareas
  - Cavity
  - Spalling
  - Graffiti
  - Weathering
  - Restformwork
  - ExposedRebars
  - Bearing
  - EJoint
  - Drainage
  - PEquipment
  - JTape
  - WConccor