#@package _global_
logging:
  logdir: /dkfz/cluster/gpu/checkpoints/OE0441/l727r/logs
  progressbar: False

paths:
  Cityscapes: /dkfz/cluster/gpu/data/OE0441/l727r/cityscapes
  VOC2010_Context: /dkfz/cluster/gpu/data/OE0441/l727r/VOC2010_Context
  EndoCV2022: /dkfz/cluster/gpu/data/OE0441/l727r/EndoCV2022
  HidaHackathon2022: /dkfz/cluster/gpu/data/OE0441/l727r/Hackathon_500/Hackathon_data
  AGGC2022: /dkfz/cluster/gpu/data/OE0441/l727r/AGGC2022
  DIADEM: /dkfz/cluster/gpu/data/OE0441/l727r/Dataset101_DIADEM
  #COMPUTING: /dkfz/cluster/gpu/data/OE0441/l727r/Dataset250_COMPUTING_it0
  COMPUTING: /dkfz/cluster/gpu/data/OE0441/l727r/nnUNet_raw/Dataset254_COMPUTING_it4
  Solar_Hydrogen: /dkfz/cluster/gpu/data/OE0441/l727r/Solar_Hydrogen/New_TrainingData
  Fishinspector: /dkfz/cluster/gpu/data/OE0441/l727r/Dataset222_Fishinspector
  dacl10k: /dkfz/cluster/gpu/data/OE0441/l727r/dacl10k_dataset_512
