#@package _global_
CALLBACKS:
  tqdm_progressbar: ~
pl_trainer:
    enable_progress_bar: false

LOGDIR: /gpu/checkpoints/OE0441/l727r

paths:
  cityscapes:
      LABELS: /gpu/data/OE0441/l727r/cityscapes
      IMAGES: /gpu/data/common/cityscapes
  VOC2010_Context: /gpu/data/OE0441/l727r/VOC2010_Context
