#@package _global_
CALLBACKS:
  tqdm_progressbar: ~
pl_trainer:
    enable_progress_bar: False    # Discable Progressbar in this environment
    enable_checkpointing: True

LOGDIR: cluster/.../logs
paths:
  Cityscapes: /cluster/.../Datasets/cityscapes
  VOC2010_Context: /cluster/.../Datasets/VOC2010_Context
  EndoCV2022: /cluster/.../endocv2022
  HidaHackathon2022: /cluster/.../Datasets/Hackathon_500/Hackathon_data
