#@package _global_
CALLBACKS:
  tqdm_progressbar: ~
pl_trainer:
    enable_progress_bar: False
    enable_checkpointing: True

LOGDIR: /dkfz/cluster/gpu/checkpoints/OE0441/l727r

paths:
  cityscapes:
      LABELS: /dkfz/cluster/gpu/data/OE0441/l727r/cityscapes
      IMAGES: /dkfz/cluster/gpu/data/common/cityscapes
  VOC2010_Context: /dkfz/cluster/gpu/data/OE0441/l727r/VOC2010_Context
