#@package _global_
CALLBACKS:
  tqdm_progressbar: ~
pl_trainer:
    enable_progress_bar: False
    enable_checkpointing: True

LOGDIR: /dkfz/cluster/gpu/.../logs

paths:
  Cityscapes:
      LABELS: /dkfz/cluster/gpu/.../cityscapes
      IMAGES: /dkfz/cluster/gpu/data/.../cityscapes
  VOC2010_Context: /dkfz/cluster/gpu/data/.../VOC2010_Context