#@package _global_
#LOGDIR: logs/
#pl_trainer:
#  enable_checkpointing: False   #Disable checkpointing on this environment

#Path to Data of different Datasets
paths:
  Cityscapes: /home/l727r/Desktop/Datasets/cityscapes
  VOC2010_Context: /home/l727r/Desktop/Datasets/VOC2010_Context
  EndoCV2022: /home/l727r/Desktop/endocv2022/official EndoCV2022 dataset
  HidaHackathon2022: /home/l727r/Desktop/Datasets/Hackathon_500/Hackathon_data
  #AGGC2022: /media/l727r/data/AGGC2022
  AGGC2022: /home/l727r/Documents/cluster-data/AGGC2022
