#@package _global_
#LOGDIR: logs/
pl_trainer:
  enable_checkpointing: False   #Disable checkpointing on this environment

compile: False

#Path to Data of different Datasets
paths:
  Cityscapes: /media/l727r/data/Datasets/cityscapes
  VOC2010_Context: /media/l727r/data/Datasets/VOC2010_Context
  ADE20K: /media/l727r/data/Datasets/ADEChallengeData2016
  #EndoCV2022: /home/l727r/Desktop/endocv2022/official EndoCV2022 dataset
  EndoCV2022: /home/l727r/Documents/E132-Projekte/Projects/Helmholtz_Imaging_ACVL/DKFZ_2022_EndoCV/official EndoCV2022 dataset
  #HidaHackathon2022: /home/l727r/Desktop/Datasets/Hackathon_500/Hackathon_data
  HidaHackathon2022: /media/l727r/data/Datasets/Hackathon_500/Hackathon_data
  #AGGC2022: /media/l727r/data/AGGC2022
  #AGGC2022: /home/l727r/Documents/cluster-data/AGGC2022
  AGGC2022: /home/l727r/Documents/cluster-data/AGGC2022
  DIADEM: /home/l727r/Desktop/DIADEM/Dataset101_DIADEM
  #COMPUTING: /media/l727r/data/nnUNet/nnUNetv2_raw/Dataset250_COMPUTING_it0
  COMPUTING: /media/l727r/data/nnUNet/nnUNetv2_raw/Dataset254_COMPUTING_it4
  #COMPUTING: /home/l727r/Documents/cluster-data/nnUNet_raw/Dataset253_COMPUTING_it3
  PennFudan: /home/l727r/Desktop/Datasets/PennFudanPed
  Solar_Hydrogen: /home/l727r/Documents/E132-Projekte/Projects/Helmholtz_Imaging_ACVL/HZDR_2022_Solar_Hydrogen/New_TrainingData
  #Solar_Hydrogen: /home/l727r/Documents/E132-Projekte/Projects/Helmholtz_Imaging_ACVL/HZDR_2022_Solar_Hydrogen/DefaultDataset
  Solar_Hydrogen_Karol: /media/l727r/data/Solar_Hydrogen/TrainingData_Karol
  Fishinspector: /media/l727r/data/UFZ_2023_Fishinspector/Dataset222_Fishinspector
  dacl10k: /media/l727r/data/Datasets/dacl10k/dacl10k_dataset
