#@package _global_

#Path to Data of different Datasets
paths:
  Cityscapes: /home/.../Datasets/cityscapes
  VOC2010_Context: /home/.../VOC2010_Context
  PennFudan: /home/.../Datasets/PennFudanPed
