#@package _global_
LOGDIR: logs/

paths:
  cityscapes: /home/l727r/Desktop/Datasets/cityscapes
  VOC2010_Context: /home/l727r/Desktop/Datasets/VOC2010_Context
  EndoCV2022: /home/l727r/Desktop/endocv2022/official EndoCV2022 dataset
