#@package _global_
#LOGDIR: logs/
pl_trainer:
  enable_checkpointing: True   # Enable checkpointing on this environment

#Path to Data of different Datasets
paths:
  Cityscapes: /home/.../Datasets/cityscapes
  VOC2010_Context: /home/.../Datasets/VOC2010_Context
  EndoCV2022: /home/.../endocv2022
  HidaHackathon2022: /home/.../Datasets/Hackathon_500/Hackathon_data
