#@package _global_

# define and configure the dataset class which is called by hydra
dataset:
  _target_:     datasets.VOC2010_Context.VOC2010_Context.VOC2010_Context_dataset
  root:         ${paths.VOC2010_Context}
  ignore_index: ${DATASET.IGNORE_INDEX}
  num_classes:  ${DATASET.NUM_CLASSES}

# additional information about the dataset
DATASET:
  NAME:         "VOC2010_Context_60"
  NUM_CLASSES:  60
  IGNORE_INDEX: 255
  #INFORMATION ABOUT DS, NOT NEEDED
  SIZE:
    TRAIN: 4998
    VAL:   5103
    TEST:  0
  #OPTIONAL - JUST IF CLASS LOGGING RESULTS ARE WANTED
  CLASS_LABELS:
    - background
    - aeroplane
    - bag
    - bed
    - bedclothes
    - bench
    - bicycle
    - bird
    - boat
    - book
    - bottle
    - building
    - bus
    - cabinet
    - car
    - cat
    - ceiling
    - chair
    - cloth
    - computer
    - cow
    - cup
    - curtain
    - dog
    - door
    - fence
    - floor
    - flower
    - food
    - grass
    - ground
    - horse
    - keyboard
    - light
    - motorbike
    - mountain
    - mouse
    - person
    - plate
    - platform
    - pottedplant
    - road
    - rock
    - sheep
    - shelves
    - sidewalk
    - sign
    - sky
    - snow
    - sofa
    - table
    - track
    - train
    - tree
    - truck
    - tvmonitor
    - wall
    - water
    - window
    - wood

