LOGDIR: "logs/"
MODEL:
  FILE: 'config/models/hrnet.yaml'
  PRETRAINED: true
DATASET:
  NUM_WORKERS: 4
  BATCH_SIZE: 6
  #VALIDATION_BATCH_SIZE: 2
  FILE: "config/datasets/Cityscape_19.yaml"
  #FILE: "config/datasets/Cityscape_Coarse_19.yaml"
TRAIN:
  EPOCHS: 200
  MIXED_PRECISION: True
  BENCHMARK: True
  TRAINER:
    sync_batchnorm: True,
  #  reload_dataloaders_every_epoch: true
  #  accumulate_grad_batches: 2
  #
  OPTIMIZER: sgd
  LR: 0.01 #LR: 0.01445439770745928
  WD: 0.0005
  MOMENTUM: 0.9
  LR_SCHEDULER: poly
  LOSSFUNCTION:
    - "wCE"
  LOSSWEIGHT:
    - 1.0
#TEST:
AUGMENTATIONS:
  TRAIN:
    RandomScale:
      scale_limit: [ -0.5,1.0 ]
      p: 1.0
    RandomCrop:
      height: 512
      width: 1024
    HorizontalFlip:
      p: 0.5
    #Resize:
    #    height: 512
    #    width: 1024
    #    p: 1.0
    Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    ToTensorV2:
  TEST:
    FROM_DICT:
    Normalize:
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    ToTensorV2: