dataset: cityscaped, ...
model: hrnet, ...
metric: IoU, Dice
#  per_class: True False
image_type: RGB,G, ...
label_type: sem_seg, inst_seg, multi_seg, partly_labeled
train_split: train-val, cv
sampling: None, balanced



trainer:
callbacks:
augmentation:
optimizer:
lr_scheduler:
logger:
loss:
hp:
  epochs:
  lr: