trainer:
metric:
  - per_img
  - global
model:
dataset:
  - CV or Train-val split
  - sampling
optimizer:
lr_scheduler:
callbacks:
logger:
augmentation:
  - augmentation_cfg
  - test
  - train
  - val
  - predict?
experiment:
environment:


visualization:
  - num predictions
  - colormap
validation:
  - TTA
  - Pathing
testing:
  - TTA
    - flip_h
    - flip_v
    - scale
  - patching
  - ensemble
    - best
    - last
predict:
  - input_dir
  - output_dir
  - softmax
  - TTA
    - flip_h
    - flip_v
    - scale
  - patching
  - ensemble
    - best
    - last