#@package _global_

###### Main Config File for Testing ######
# This config shows an overview about all parameters and there default values
# Most of the settings are taken from training.yaml and only minor things are changed

###### Hydra's Default List ######
defaults:
  - training                  # Use the settings defined in the training config (training.yaml)
  - _self_                    # Overwrite behaviour

###### Checkpoint Directory ######
ckpt_dir: ???   # (Required) Path to the Checkpoint which should be tested/validated

###### Hydra ######
hydra:
  run:
    dir: ${ckpt_dir}/testing/${now:%Y-%m-%d_%H-%M-%S}   # Log the results into the checkpoint folder
