#@package _global_

# Default List
# Use baseline.yaml and only change/override a few parts
defaults:
  - baseline
  - _self_

# (Required) Path to the Checkpoint which should be tested/validated
ckpt_dir: ???

# Customizations of Hydra, change hydra/run/dir to ckpt_dir
hydra:
  output_subdir: testing/hydra
  run:
    dir: ${ckpt_dir}
  sweep:
    dir: multi_run_${hydra.run.dir}
    subdir: ${hydra.job.num}
  job_logging:
    handlers:
      file:
        #filename: testing/${hydra.job.name}.log
        filename: ${hydra.job.name}.log