_target_: albumentations.Compose
transforms:
  - _target_: albumentations.HorizontalFlip
    p: 0.5
  - _target_: albumentations.Normalize
    mean: ${augmentation_cfg.mean}
    std: ${augmentation_cfg.std}
  - _target_: albumentations.pytorch.ToTensorV2
