_target_: albumentations.Compose
transforms:
  - _target_: albumentations.PadIfNeeded
    min_height: ${augmentation_cfg.pad_size[0]}
    min_width: ${augmentation_cfg.pad_size[1]}
    border_mode: ${augmentation_cfg.pad_mode}
    value: ${augmentation_cfg.pad_val}
    mask_value: ${augmentation_cfg.pad_mask}
  - _target_: albumentations.Normalize
    mean: ${augmentation_cfg.mean}
    std: ${augmentation_cfg.std}
  - _target_: albumentations.pytorch.ToTensorV2