_target_: albumentations.Compose
transforms:
  - _target_: albumentations.PadIfNeeded
    min_height: ${augmentation.cfg.pad_size[0]}
    min_width: ${augmentation.cfg.pad_size[1]}
    border_mode: ${augmentation.cfg.pad_mode}
    value: ${augmentation.cfg.pad_val}
    mask_value: ${augmentation.cfg.pad_mask}
  - _target_: albumentations.Normalize
    mean: ${augmentation.cfg.mean}
    std: ${augmentation.cfg.std}
  - _target_: albumentations.pytorch.ToTensorV2