_target_: albumentations.Compose
transforms:
  - _target_: albumentations.PadIfNeeded
    min_height: ${augmentation.cfg.crop_size[0]}
    min_width: ${augmentation.cfg.crop_size[1]}
  - _target_: albumentations.RandomCrop
    height: ${augmentation.cfg.crop_size[0]}
    width: ${augmentation.cfg.crop_size[1]}
  - _target_: src.augmentations.randaugment.RandAugment
    N: ${augmentation.cfg.N}
    M: ${augmentation.cfg.M}
    mode: 2
    p: 0.5
  - _target_: albumentations.HorizontalFlip
    p: 0.5
  - _target_: albumentations.Normalize
    mean: ${augmentation.cfg.mean}
    std: ${augmentation.cfg.std}
  - _target_: albumentations.pytorch.ToTensorV2
