_target_: albumentations.Compose
transforms:
  - _target_: src.augmentations.randaugment.RandAugment_light_scale
    N: ${augmentation.cfg.N}
    M: ${augmentation.cfg.M}
    mode: 2
    p: 0.5
  - _target_: albumentations.HorizontalFlip
    p: 0.25
  - _target_: albumentations.VerticalFlip
    p: 0.25
  - _target_: albumentations.Normalize
    mean: ${augmentation.cfg.mean}
    std: ${augmentation.cfg.std}
  - _target_: albumentations.pytorch.ToTensorV2