_target_: albumentations.Compose
transforms:
  - _target_: albumentations.Resize
    height: ${augmentation.cfg.resize_size[0]}
    width: ${augmentation.cfg.resize_size[1]}
  - _target_: albumentations.ColorJitter
    brightness: 0.4
    contrast: 0.4
    saturation: 0.2
    hue: 0.2
    p: 0.5
  - _target_: albumentations.HorizontalFlip
    p: 0.25
  - _target_: albumentations.VerticalFlip
    p: 0.25
  - _target_: albumentations.Normalize
    mean: ${augmentation.cfg.mean}
    std: ${augmentation.cfg.std}
  - _target_: albumentations.pytorch.ToTensorV2

