_target_: albumentations.Compose
transforms:
  - _target_: albumentations.Resize
    height: ${augmentation.cfg.resize_size[0]}
    width: ${augmentation.cfg.resize_size[1]}
  - _target_: albumentations.Normalize
    mean: ${augmentation.cfg.mean}
    std: ${augmentation.cfg.std}
  - _target_: albumentations.pytorch.ToTensorV2

