_target_: albumentations.Compose
transforms:
  - _target_: albumentations.RandomScale
    scale_limit: ${augmentation.cfg.scale_limit}
    p: 1.0
  - _target_: albumentations.PadIfNeeded
    min_height: ${augmentation.cfg.crop_size[0]}
    min_width: ${augmentation.cfg.crop_size[1]}
  - _target_: albumentations.RandomCrop
    height: ${augmentation.cfg.crop_size[0]}
    width: ${augmentation.cfg.crop_size[1]}
  - _target_: albumentations.ColorJitter
    brightness: 0.4
    contrast: 0.4
    saturation: 0.1
    hue: 0.1
    p: 0.5
  - _target_: albumentations.HorizontalFlip
    p: 0.25
  - _target_: albumentations.VerticalFlip
    p: 0.25
  - _target_: albumentations.Normalize
    mean: ${augmentation.cfg.mean}
    std: ${augmentation.cfg.std}
  - _target_: albumentations.pytorch.ToTensorV2