dataset:
  _target_:     # Path to the Dataset File
  arg1: ...     # Input Argument for the dataset

name: MyDataset                 # Name of the dataset, needed for logging
num_classes:                    # Number of classes in the dataset
# ignore_index: 255             # Ignore Index of the dataset (not required)
# class_weights: [...]          # weights of classes, when using weighted loss functions (not required)
segmentation_type: semantic     # Typ of segmentation, one of - semantic, instance or multilabel
class_labels:                   # Name for each class
  - class_1
  - ...