dataset:
  _target_: src.datasets.base_datasets.multilabel.MultilabelSamplingCVDataset     # Path to the Dataset File
  root:                         # Root to the data
  img_folder:                   # Folder to the images for training
  img_folder_val:               # Folder to the images for validation
  img_folder_test:              # Folder to the images for testing (if not defined img_folder_val is used)
  label_folder:                 # Folder to the labels for training
  label_folder_val:             # Folder to the labels for validation
  label_folder_test:            # Folder to the labels for testing (if not defined label_folder_val is used)
  dtype: ".png"                 # Data type of the image files
  dtype_mask: ".png"            # Data type of the label files
  fold: ${fold}                 # Fold which should be used for training
  num_classes: ${dataset.num_classes}             # Number of Classes
  batch_size: ${batch_size}     # Batch size, needed for computing the number of steps
  patch_size: ${augmentation.cfg.crop_size}       # Patch size which should be used for patching
  scale_limit: ${augmentation.cfg.scale_limit}    # Scale limit for scaling the patches

name: MyDataset                 # Name of the dataset, needed for logging
num_classes:                    # Number of classes in the dataset
# ignore_index: 255             # Ignore Index of the dataset (not required)
# class_weights: [...]          # weights of classes, when using weighted loss functions (not required)
segmentation_type: multilabel   # Typ of segmentation, one of - semantic, instance or multilabel
class_labels:                   # Name for each class
  - class_1
  - ...