dataset:
  _target_: src.datasets.base_datasets.base.BaseDataset     # Path to the Dataset File
  root:                         # Root to the data
  img_folder:                   # Folder to the images for training
  img_folder_val:               # Folder to the images for validation
  img_folder_test:              # Folder to the images for testing (if not defined img_folder_val is used)
  label_folder:                 # Folder to the labels for training
  label_folder_val:             # Folder to the labels for validation
  label_folder_test:            # Folder to the labels for testing (if not defined label_folder_val is used)
  dtype: ".png"                 # Data type of the image files
  dtype_mask: ".png"            # Data type of the label files

name: MyDataset                 # Name of the dataset, needed for logging
num_classes:                    # Number of classes in the dataset
# ignore_index: 255             # Ignore Index of the dataset (not required)
# class_weights: [...]          # weights of classes, when using weighted loss functions (not required)
segmentation_type: semantic     # Typ of segmentation, one of - semantic, instance or multilabel
class_labels:                   # Name for each class
  - class_1
  - ...