#@package _global_
defaults:
  - override /data_augmentation: AGGC2022_norm
  #- override /data_augmentation: EndoCV2022
  - override /hyperparameters: AGGC2022
  - override /metric: Dice_AGGC2022
# dataset is used to initialize your custom dataset,
# _target_: should point to your dataset class
# afterwards you can handle your custom input arguments which are used to initialize the dataset
dataset:
  #_target_: datasets.AGGC2022.AGGC2022_dataset.get_dataset
  _target_: datasets.AGGC2022.AGGC2022_test.get_dataset
  #_target_: datasets.AGGC2022.AGGC2022.AGGC2022_tiff_dataset
  data_dir: ${paths.AGGC2022}
  fold: 0
  sampling: point
  NumSamplesPerSubject: 500 #1000
  PatchSize: 512
# DATASET is used to store information about the dataset which are needed during training
DATASET:
  # Required dataser arguments
  NAME: AGGC2022           # Used for the logging directory
  NUM_CLASSES: 6    # Needed for defining the model and the metrics
  # (Optional) but needed if ignore index should be used
  IGNORE_INDEX: -100   # Needed for the loss function, if no ignore indes set to 255 or another number
                   # which do no occur in your dataset
  # (Optional) needed if weighted lossfunctions are used
  #CLASS_WEIGHTS: [ 0.9, 1.1, ...]
  # (Optional) can be used for nicer for logging
  CLASS_LABELS:
    - Background
    - Stroma
    - Normal
    - G3
    - G4
    - G5