#@package _global_
#DEFINING THE DEFAULT DATA AUGMENTATION FOR THIS DATASET
defaults:
  - override /data_augmentation: scale_and_crop
  - override /hyperparameters: Cityscapes
#SETTING UP DATASET IMPLEMENTATION, WILL BE CALLED USING HYDRA
dataset:
  _target_: datasets.Cityscapes.Cityscape_fine_coarse.Cityscape_fine_coarse_dataset
  root:     ${paths.Cityscapes}

AUGMENTATIONS:
  scale_limit: [-0.5, 1.0]
  crop_size: [512, 1024]
  mean: [ 0.485, 0.456, 0.406 ]
  std: [ 0.229, 0.224, 0.225 ]

DATASET:
  NAME:         "Cityscapes_fine_coarse"
  NUM_CLASSES:  19
  IGNORE_INDEX: 255
  #NEEDED IF WEIGHTED LOSSFUNCTIONS ARE USED
  CLASS_WEIGHTS: [ 0.8373, 0.918, 0.866, 1.0345,1.0166,
                   0.9969, 0.9754, 1.0489, 0.8786, 1.0023,
                   0.9539, 0.9843,1.1116, 0.9037, 1.0865,
                   1.0955, 1.0865, 1.1529, 1.0507 ]
  #INFORMATION ABOUT DS, NOT NEEDED
  SIZE:
    TRAIN: 22972
    VAL:   500
  #OPTIONAL - JUST IF CLASS LOGGING RESULTS ARE WANTED
  CLASS_LABELS:
    - road
    - sidewalk
    - building
    - wall
    - fence
    - pole
    - traffic light
    - traffic sign
    - vegetation
    - terrain
    - sky
    - person
    - rider
    - car
    - truck
    - bus
    - train
    - motorcycle
    - bicycle
