#@package _global_
defaults:
  - override /data_augmentation: COMPUTING
  - override /metric: Dice_COMPUTING
# dataset is used to initialize your custom dataset,
# _target_: should point to your dataset class
# afterwards you can handle your custom input arguments which are used to initialize the dataset
dataset:
  _target_: datasets.COMPUTING.COMPUTING.Computing_dataset
  root: ${paths.COMPUTING}               #the root if defined in config/environment/used_env.yaml
  fold: 0
# DATASET is used to store information about the dataset which are needed during training
DATASET:
  # Required dataser arguments
  NAME: COMPUTING            # Used for the logging directory
  NUM_CLASSES: 8    # Needed for defining the model and the metrics
  # (Optional) but needed if ignore index should be used
  IGNORE_INDEX: 8   # Needed for the loss function, if no ignore indes set to 255 or another number
                   # which do no occur in your dataset
  # (Optional) needed if weighted lossfunctions are used
  #CLASS_WEIGHTS: [ 0.9, 1.1, ...]
  # (Optional) can be used for nicer for logging
  CLASS_LABELS:
    - background
    - covered_areas
    - open_pore
    - dead-end_pore
    - closed_pore
    - artifact_crater
    - artifact_blob
    - artifact_dust