#@package _global_
defaults:
  - override /data_augmentation: scale_and_crop
  - override /metric: Dice_DIADEM
  #- override /hyperparameters: Cityscapes
# dataset is used to initialize your custom dataset,
# _target_: should point to your dataset class
# afterwards you can handle your custom input arguments which are used to initialize the dataset
dataset:
  _target_: datasets.DIADEM.DIADEM.DIADEM_dataset
  root: ${paths.DIADEM}               #the root if defined in config/environment/used_env.yaml
  fold: 0

AUGMENTATIONS:
  scale_limit: [-0.4, 1.0]
  crop_size: [512, 512]
  mean: [ 0.485, 0.456, 0.406 ]
  std: [ 0.229, 0.224, 0.225 ]

# DATASET is used to store information about the dataset which are needed during training
DATASET:
  # Required dataser arguments
  NAME: DIADEM            # Used for the logging directory
  NUM_CLASSES: 2    # Needed for defining the model and the metrics
  # (Optional) but needed if ignore index should be used
  IGNORE_INDEX: 255   # Needed for the loss function, if no ignore indes set to 255 or another number
                   # which do no occur in your dataset
  # (Optional) needed if weighted lossfunctions are used
  CLASS_WEIGHTS: [0.0640028715133667, 0.9359970688819885]
  # (Optional) can be used for nicer for logging
  CLASS_LABELS:
     - background
     - islet
