#@package _global_

#DEFINING THE DEFAULT DATA AUGMENTATION FOR THIS DATASET
defaults:
  - override /data_augmentation: EndoCV2022
  - override /hyperparameters: EndoCV2022
  - override /metric: binary_Dice
#SETTING UP DATASET IMPLEMENTATION, WILL BE CALLED USING HYDRA
dataset:
  _target_: datasets.EndoCV2022.EndoCV2022.EndoCV2022_dataset
  root:     ${paths.EndoCV2022}
  fold:     ${DATASET.FOLD}

DATASET:
  NAME:         "EndoCV2022"
  FOLD:         0
  NUM_CLASSES:  2
  IGNORE_INDEX: 255
  #N EEDED TO COMPUTE THE MAX NUMBER OF STEPS
  SIZE:
    TRAIN: 2469
    VAL:   826
    TEST:  0
  # OPTIONAK FOR LOGGING
  CLASS_LABELS:
    - background
    - polyp

