#@package _global_
# afterwards you can handle your custom input arguments which are used to initialize the dataset
dataset:
  _target_: datasets.Fishinspector.Fishinspector.Fishinspector_dataset_partly_labeled
  root: ${paths.Fishinspector}               #the root if defined in config/environment/used_env.yaml
  img_folder: imagesTr
  label_folder: labelsTr
  fold: 0
  num_classes: ${DATASET.NUM_CLASSES}

# DATASET is used to store information about the dataset which are needed during training
DATASET:
  max_size: (345,1024)
  min_size: (190,776)
  # Required dataser arguments
  NAME: Fishinspector            # Used for the logging directory
  NUM_CLASSES: 16    # Needed for defining the model and the metrics
  # (Optional) but needed if ignore index should be used
  IGNORE_INDEX: 255   # Needed for the loss function, if no ignore indes set to 255 or another number
  CLASS_LABELS:
    - contour_LAT
    - yolk_DV
    - mouth_tip_LAT
    - eye_LAT
    - pericard_LAT
    - eye1_DV
    - contour_DV
    - fin1_DV
    - otolith1_LAT
    - otolith2_LAT
    - eye2_DV
    - notochord_LAT
    - swimbladder_LAT
    - yolk_LAT
    - fin2_DV
    - pigmentation_LAT