#@package _global_

#DEFINING THE DEFAULT DATA AUGMENTATION FOR THIS DATASET
defaults:
  #- override /data_augmentation: HidaHackathon2022
  - override /hyperparameters: HidaHackathon2022
  #- override /metric: IoU_HidaHackathon2022

#SETTING UP DATASET IMPLEMENTATION, WILL BE CALLED USING HYDRA
dataset:
  _target_: datasets.HidaHackathon2022.HidaHackathon2022.HidaHackathon2022_dataset
  root:     ${paths.HidaHackathon2022}
  fold:     ${DATASET.FOLD}

DATASET:
  NAME:         "HidaHackathon2022"
  FOLD:         0
  NUM_CLASSES:  3
  IGNORE_INDEX: 255
  LABELS:
    - background
    - terrace
    - wall
  #CLASS_WEIGHTS: [ 0.0395, 0.9754, 0.9851 ]
  CLASS_WEIGHTS: [ 0.3475, 13.7498, 20.1881]


