name: PennFudan
num_classes:  2
root: ${paths.PennFudan}

img_folder: PNGImages
label_folder: PedMasks
img_folder_val: ""
label_folder_val: ""

ignore_index: 0
segmentation_type: instance
class_labels:
  - background
  - person
