# define and configure the dataset class which is called by hydra
dataset:
  #_target_: datasets.PennFudan.PennFudan.PennFudanDataset
  _target_: src.datasets.Base_Datasets.instance_segmentation.Instance_Dataset_CV
  root: ${paths.PennFudan}
  img_folder: PNGImages
  label_folder: PedMasks

# additional information about the dataset
name: PennFudan
num_classes:  2
ignore_index: 0
segmentation_type: instance
class_labels:
  - background
  - person