dataset:
  _target_: src.datasets.Solar_Hydrogen.Solar_Hydrogen.Custom_dataset
  root:      ${paths.Solar_Hydrogen_Karol} #the root to the data

name: Solar_Hydrogen_Karol
num_classes: 2
segmentation_type: instance
class_labels:
   - background
   - bubble
