#@package _global_

# define and configure the dataset class which is called by hydra
dataset:
  _target_: datasets.Solar_Hydrogen.Solar_Hydrogen.Custom_dataset
  root:      ${paths.Solar_Hydrogen} #the root to the data

# additional information about the dataset
DATASET:
  NAME: Solar_Hydrogen
  NUM_CLASSES: 2
  CLASS_LABELS:
     - background
     - bubble
