dataset:
  _target_: src.datasets.Solar_Hydrogen.Solar_Hydrogen.Solar_Hydrogen_Dataset
  root:      ${paths.Solar_Hydrogen} #the root to the data
  dtype: ".tif"
  img_folder: ground_truth/images
  label_folder: none

name: Solar_Hydrogen
num_classes: 2
segmentation_type: instance
class_labels:
   - background
   - bubble
