#@package _global_

#DEFINING THE DEFAULT DATA AUGMENTATION FOR THIS DATASET
defaults:
  - override /data_augmentation: VOC2010_Context
  - override /hyperparameters: VOC2010_Context
#SETTING UP DATASET IMPLEMENTATION, WILL BE CALLED USING HYDRA
dataset:
    _target_: datasets.VOC2010_Context.VOC2010_Context_dataset
    root: ${paths.VOC2010_Context}
    ignore_index: ${DATASET.IGNORE_INDEX}
    num_classes: ${DATASET.NUM_CLASSES}

DATASET:
  #PATH PARAMETERS FOR THIS DATASET
  #ROOT: "/home/l727r/Desktop/Datasets/VOC2010_Context"
  #CLUSTER_ROOT: /gpu/data/OE0441/l727r/VOC2010_Context
  ##NEEDED PARAMETERS
  NAME: "VOC2010_Context"
  NUM_CLASSES: 59
  IGNORE_INDEX: 255
  #NEEDED IF POLY LR is used
  SIZE:
    TRAIN: 4998
    VAL: 5103
    TEST: 0
  #NEEDED IF WEIGHTED LOSSFUNCTIONS ARE USED
  CLASS_LABELS:
    - aeroplane
    - bag
    - bed
    - bedclothes
    - bench
    - bicycle
    - bird
    - boat
    - book
    - bottle
    - building
    - bus
    - cabinet
    - car
    - cat
    - ceiling
    - chair
    - cloth
    - computer
    - cow
    - cup
    - curtain
    - dog
    - door
    - fence
    - floor
    - flower
    - food
    - grass
    - ground
    - horse
    - keyboard
    - light
    - motorbike
    - mountain
    - mouse
    - person
    - plate
    - platform
    - pottedplant
    - road
    - rock
    - sheep
    - shelves
    - sidewalk
    - sign
    - sky
    - snow
    - sofa
    - table
    - track
    - train
    - tree
    - truck
    - tvmonitor
    - wall
    - water
    - window
    - wood

