#@package _global_

#DEFINING WHICH DATA AUGMENTATIONS AND HYPERPARAMETERS ARE USED FOR THIS DATASET
defaults:
  - override /data_augmentation: scale_crop_VOC2010
  - override /hyperparameters: VOC2010_Context
#SETTING UP DATASET IMPLEMENTATION, WILL BE CALLED USING HYDRA
dataset:
  _target_:     datasets.VOC2010_Context.VOC2010_Context.VOC2010_Context_dataset
  root:         ${paths.VOC2010_Context}
  ignore_index: ${DATASET.IGNORE_INDEX}
  num_classes:  ${DATASET.NUM_CLASSES}

AUGMENTATIONS:
  scale_limit: [-0.5, 1.0]
  crop_size: [520, 520]
  mean: [ 0.485, 0.456, 0.406 ]
  std: [ 0.229, 0.224, 0.225 ]

TESTING:
  SCALES: [ 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0 ]
  FLIP: False
  BINARY_FLIP: True
  OVERRIDES:
    - val_batch_size=1

DATASET:
  NAME:         "VOC2010_Context_60"
  NUM_CLASSES:  60
  IGNORE_INDEX: 255
  #INFORMATION ABOUT DS, NOT NEEDED
  SIZE:
    TRAIN: 4998
    VAL:   5103
    TEST:  0
  #OPTIONAL - JUST IF CLASS LOGGING RESULTS ARE WANTED
  CLASS_LABELS:
    - background
    - aeroplane
    - bag
    - bed
    - bedclothes
    - bench
    - bicycle
    - bird
    - boat
    - book
    - bottle
    - building
    - bus
    - cabinet
    - car
    - cat
    - ceiling
    - chair
    - cloth
    - computer
    - cow
    - cup
    - curtain
    - dog
    - door
    - fence
    - floor
    - flower
    - food
    - grass
    - ground
    - horse
    - keyboard
    - light
    - motorbike
    - mountain
    - mouse
    - person
    - plate
    - platform
    - pottedplant
    - road
    - rock
    - sheep
    - shelves
    - sidewalk
    - sign
    - sky
    - snow
    - sofa
    - table
    - track
    - train
    - tree
    - truck
    - tvmonitor
    - wall
    - water
    - window
    - wood

