dataset:
  _target_: src.datasets.Base_Datasets.cross_validation.CV_Dataset
  root:     ${paths.COMPUTING}
  img_folder: "imagesTr"
  label_folder: "labelsTr"
  fold: ${fold}

name: COMPUTING_it4
num_classes: 7
ignore_index: 7
class_labels:
  - background
  - areas_wo_pores
  - open_pore
  - closed_pore
  - internal_structure
  - artifact_blob
  - artifact_dust