#@package _global_
# afterwards you can handle your custom input arguments which are used to initialize the dataset
dataset:
  _target_: src.datasets.COMPUTING.COMPUTING.Computing_dataset
  root: ${paths.COMPUTING}               #the root if defined in config/environment/used_env.yaml
  fold: ${fold}

# DATASET is used to store information about the dataset which are needed during training
DATASET:
  # Required dataser arguments
  NAME: COMPUTING_it3            # Used for the logging directory
  NUM_CLASSES: 7    # Needed for defining the model and the metrics
  # (Optional) but needed if ignore index should be used
  IGNORE_INDEX: 7   # Needed for the loss function, if no ignore indes set to 255 or another number
                   # which do no occur in your dataset
  # (Optional) needed if weighted lossfunctions are used
  #CLASS_WEIGHTS: [ 0.9, 1.1, ...]
  # (Optional) can be used for nicer for logging
  CLASS_LABELS:
    - background
    - covered_areas
    - open_pore
    - dead-end_pore
    - closed_pore
    - artifact_crater
    - artifact_blob
    - artifact_dust