#@package _global_
AUGMENTATIONS:
  TRAIN:
    - Compose:
        transforms:
          - StrongAugmentor:
              p: 0.5
          - VahadaneNormalizer:
              p: 1
          - ColorJitter:
              brightness: 0.2
              contrast: 0.2
              saturation: 0.2
              hue: 0.2
              p: 0.5
          - JPEGcompressor:
              p: 0.5
          - Normalize:
              mean: [ 0.485, 0.456, 0.406 ]
              std: [ 0.229, 0.224, 0.225 ]
          - ToTensorV2:
  VALIDATION:
    - Compose:
        transforms:
          - VahadaneNormalizer:
              p: 1
          - Normalize:
              mean: [ 0.485, 0.456, 0.406 ]
              std: [ 0.229, 0.224, 0.225 ]
          - ToTensorV2:
  TEST:
    - Compose:
        transforms:
          - VahadaneNormalizer:
              p: 1
          - Normalize:
              mean: [ 0.485, 0.456, 0.406 ]
              std: [ 0.229, 0.224, 0.225 ]
          - ToTensorV2: