#@package _global_
# old name AGGC2022_2
AUGMENTATIONS:
  TRAIN:
    - Compose:
        transforms:
          - ColorJitter:
              brightness: 0.2
              contrast: 0.2
              saturation: 0.2
              hue: 0.2
              p: 0.5
          - RandomRotate90:
              p: 0.25
          - Transpose:
              p: 0.25
          #- JPEGcompressor:
          #    p: 0.5
          - Normalize:
              mean: [ 0.485, 0.456, 0.406 ]
              std: [ 0.229, 0.224, 0.225 ]
          - ToTensorV2:
  VALIDATION:
    - Compose:
        transforms:
          - Normalize:
                mean: [ 0.485, 0.456, 0.406 ]
                std: [ 0.229, 0.224, 0.225 ]
          - ToTensorV2:
  TEST:
    - Compose:
        transforms:
          - Normalize:
              mean: [ 0.485, 0.456, 0.406 ]
              std: [ 0.229, 0.224, 0.225 ]
          - ToTensorV2: