#@package _global_
AUGMENTATIONS:
  VALIDATION:
    - Compose:
        transforms:
           - Normalize:
              mean: [ 0.485, 0.456, 0.406 ]
              std: [ 0.229, 0.224, 0.225 ]
           - ToTensorV2:
  TEST: ${AUGMENTATIONS.VALIDATION}
  TRAIN:
    - Compose:
        transforms:
          - RandomScale:
              scale_limit: [ -0.5, 1.0 ]
              p: 1.0
          - RandomCrop:
              height: 512
              width: 1024
          - RGBShift:
              r_shift_limit: 10
              g_shift_limit: 10
              b_shift_limit: 10
          - GaussianBlur:
          - HorizontalFlip:
              p: 0.5
          - Normalize:
              mean: [ 0.485, 0.456, 0.406 ]
              std: [ 0.229, 0.224, 0.225 ]
          - ToTensorV2:
