#@package _global_
AUGMENTATIONS:
  VALIDATION:
    - Compose:
        transforms:
          - Normalize:
              mean: [ 0.485, 0.456, 0.406 ]
              #mean: [123.675, 116.28, 103.53]
              std: [ 0.229, 0.224, 0.225 ]
              #std: [58.395, 57.12, 57.375]
          - ToTensorV2:
  TEST: ${AUGMENTATIONS.VALIDATION}
  TRAIN:
    - Compose:
        transforms:
          - RandomScale:
              scale_limit: [ -0.5, 1.0 ]
              p: 1.0
          - RandomCrop:
              height: 512
              width:  1024
          - HorizontalFlip:
              p: 0.5
          - Normalize:
              mean: [ 0.485, 0.456, 0.406 ]
              #mean: [ 123.675, 116.28, 103.53 ]
              std: [ 0.229, 0.224, 0.225 ]
              #std: [ 58.395, 57.12, 57.375 ]
          - ToTensorV2:
