#@package _global_
AUGMENTATIONS:
  TRAIN:
    - Compose:
        transforms:
          - RandomScale:
              scale_limit: [ -0.25, 1.25 ]
              p: 1.0
          - RandomCrop:
              height: 512
              width:  512
          - HorizontalFlip:
              p: 0.5
          - VerticalFlip:
              p: 0.5
          - ColorJitter:
              brightness: 0
              saturation: 0
              hue: 0
              p: 0.3
          - ColorJitter:
              contrast: 0
              saturation: 0
              hue: 0
              p: 0.3
#          - RandAugment_Histo:
#              N: 3
#              M: 3
#              mode: 2
#              p: 1
#          - randAugment_AGGC_strong:
#              N: 2
#              M: 5
#              p: 0.5
          - Normalize:
              mean: [ 0.485, 0.456, 0.406 ]
              std: [ 0.229, 0.224, 0.225 ]
          - ToTensorV2:
  VALIDATION:
    - Compose:
        transforms:
#          - RandomCrop:
#              height: 512
#              width: 512
          - Normalize:
              mean: [ 0.485, 0.456, 0.406 ]
              std: [ 0.229, 0.224, 0.225 ]
          - ToTensorV2:
  TEST:
    - Compose:
        transforms:
          - Normalize:
              mean: [ 0.485, 0.456, 0.406 ]
              std: [ 0.229, 0.224, 0.225 ]
          - ToTensorV2: