#@package _global_
AUGMENTATIONS:
  scale_limit: [-0.5, 1.0]
  crop_size: [512, 512]
  mean: [ 0.485, 0.456, 0.406 ]
  std: [ 0.229, 0.224, 0.225 ]
  TRAIN:
    - Compose:
        transforms:
          - RandomCrop:
              height: ${AUGMENTATIONS.crop_size[0]}
              width: ${AUGMENTATIONS.crop_size[1]}
          - ToTensorV2:
  VALIDATION:
    - Compose:
        transforms:
          - ToTensorV2:
  TEST: ${AUGMENTATIONS.VALIDATION}
