#@package _global_
AUGMENTATIONS:
  TRAIN:
    RandomScale:
      scale_limit: [ -0.5,1.0 ]
      p: 1.0
    PadIfNeeded:
      min_height: 768
      min_width: 768
    RandomCrop:
      height: 768
      width: 768
    #ColorJitter:
    #  brightness: 9
    #  #brightness: [0,10]
    #  contrast: 0
    #  saturation: 0
    #  hue: 0
    HorizontalFlip:
      p: 0.5
    Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    ToTensorV2:
  TEST:
    Normalize:
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    ToTensorV2: