#@package _global_
AUGMENTATIONS:
  TRAIN:
    - Compose:
        transforms:
          - ToTensorV2:
  VALIDATION:
    - Compose:
        transforms:
          - ToTensorV2:
  TEST:
    - Compose:
        transforms:
          - ToTensorV2:
