#@package _global_
AUGMENTATIONS:
  TRAIN:
    - Compose:
        transforms:
          - RandomScale:
              scale_limit: [ 0, 1]
              p: 1.0
          - RandomCrop:
              height: 512
              width: 512
          - HorizontalFlip:
              p: 0.25
          - VerticalFlip:
              p: 0.25
          - Normalize:
              mean: [0, 0, 0,0,0,0,0,0,0,0,0]
              #mean: [0.485, 0.456, 0.406,0,0,0,0,0,0,0,0]
              std: [1, 1, 1,1,1,1,1,1,1,1,1]
              #std: [0.229, 0.224, 0.225,1,1,1,1,1,1,1,1]
          - ToTensorV2:

  VALIDATION:
    - Compose:
        transforms:
          - Normalize:
              mean: [0, 0, 0,0,0,0,0,0,0,0,0]
              #mean: [0.485, 0.456, 0.406,0,0,0,0,0,0,0,0]
              std: [1, 1, 1,1,1,1,1,1,1,1,1]
              #std: [0.229, 0.224, 0.225,1,1,1,1,1,1,1,1]
          - ToTensorV2: