#@package _global_
AUGMENTATIONS:
  mean: [ 0.485, 0.456, 0.406 ]
  std: [ 0.229, 0.224, 0.225 ]
  TRAIN:
    - Compose:
        transforms:
          - Normalize:
              mean: ${AUGMENTATIONS.mean}
              std: ${AUGMENTATIONS.std}
          - ToTensorV2:
  VALIDATION:
    - Compose:
        transforms:
          - Normalize:
              mean: ${AUGMENTATIONS.mean}
              std: ${AUGMENTATIONS.std}
          - ToTensorV2:
  TEST: ${AUGMENTATIONS.VALIDATION}
