#@package _global_
AUGMENTATIONS:
  TRAIN:
    RandomCrop:
      height: 768
      width: 768
    HorizontalFlip:
      p: 0.5
    Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    ToTensorV2:
  TEST:
    Normalize:
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    ToTensorV2: