#@package _global_
AUGMENTATIONS:
  N: 3
  M: 3
  TRAIN:
    - Compose:
        transforms:
          - RandomScale:
              scale_limit: ${AUGMENTATIONS.scale_limit}
              p: 1.0
          - PadIfNeeded:
              min_height: ${AUGMENTATIONS.crop_size[0]}
              min_width: ${AUGMENTATIONS.crop_size[1]}
          - RandomCrop:
              height: ${AUGMENTATIONS.crop_size[0]}
              width: ${AUGMENTATIONS.crop_size[1]}
          - RandAugment:
              N: ${AUGMENTATIONS.N}
              M: ${AUGMENTATIONS.M}
              mode: 2
              p: 0.5
          - VerticalFlip:
              p: 0.25
          - HorizontalFlip:
              p: 0.25
          - ToTensorV2:
  VALIDATION:
    - Compose:
        transforms:
          - ToTensorV2:
  TEST: ${AUGMENTATIONS.VALIDATION}
