#@package _global_
#@package _global_
AUGMENTATIONS:
  TRAIN:
    - Compose:
        transforms:
          - randAugment_AGGC_strong:
              N: 3
              M: 5
              p: 0.5
          - RandomRotate90:
              p: 0.25
          - Transpose:
              p: 0.125
          - Flip:
              p: 0.125
          - Normalize:
              mean: [ 0.485, 0.456, 0.406 ]
              std: [ 0.229, 0.224, 0.225 ]
          - ToTensorV2:
  VALIDATION:
    - Compose:
        transforms:
          - Normalize:
              mean: [ 0.485, 0.456, 0.406 ]
              std: [ 0.229, 0.224, 0.225 ]
          - ToTensorV2:
  TEST:
    - Compose:
        transforms:
          - Normalize:
              mean: [ 0.485, 0.456, 0.406 ]
              std: [ 0.229, 0.224, 0.225 ]
          - ToTensorV2: