#@package _global_
AUGMENTATIONS:
  scale_limit: [-0.5, 1.0]
  crop_size: [512, 512]
  mean: [ 0.485, 0.456, 0.406 ]
  std: [ 0.229, 0.224, 0.225 ]
  N: 3
  M: 3
  TRAIN:
    - Compose:
        transforms:
          - RandomScale:
              scale_limit: ${AUGMENTATIONS.scale_limit}
              p: 1.0
          - RandomCrop:
              height: ${AUGMENTATIONS.crop_size[0]}
              width: ${AUGMENTATIONS.crop_size[1]}
          - RandAugment:
              N: ${AUGMENTATIONS.N}
              M: ${AUGMENTATIONS.M}
              mode: 2
              p: 0.5
          - HorizontalFlip:
              p: 0.5
          - Normalize:
              mean: ${AUGMENTATIONS.mean}
              std: ${AUGMENTATIONS.std}
          - ToTensorV2:
  VALIDATION:
    - Compose:
        transforms:
          - Normalize:
              mean: ${AUGMENTATIONS.mean}
              std: ${AUGMENTATIONS.std}
          - ToTensorV2:
  TEST: ${AUGMENTATIONS.VALIDATION}
