#@package _global_
AUGMENTATIONS:
  TRAIN:
    - Compose:
        transforms:
          - randAugment_AGGC_light:
              N: 3
              M: 5
              p: 0.5
          - ToTensorV2:
  VALIDATION:
    - Compose:
        transforms:
          - ToTensorV2:
  TEST:
    - Compose:
        transforms:
          - ToTensorV2: