#@package _global_
AUGMENTATIONS:
  scale_limit: [-0.5,1.0]
  crop_size: [512, 512]
  mean: [ 0.485, 0.456, 0.406 ]
  std: [ 0.229, 0.224, 0.225 ]
  TRAIN:
    - Compose:
        transforms:
          - SmallestMaxSize:
              max_size: ${AUGMENTATIONS.crop_size[0]}
          - RandomScale:
              scale_limit: ${AUGMENTATIONS.scale_limit}
              p: 1.0
          - RGBShift:
              r_shift_limit: 10
              g_shift_limit: 10
              b_shift_limit: 10
          - PadIfNeeded:
              min_height: ${AUGMENTATIONS.crop_size[0]}
              min_width: ${AUGMENTATIONS.crop_size[1]}
              border_mode: 0 #"cv2.BORDER_CONSTANT"
              value: 0
              mask_value: ${DATASET.IGNORE_INDEX}
          - RandomCrop:
              height: ${AUGMENTATIONS.crop_size[0]}
              width: ${AUGMENTATIONS.crop_size[1]}
          - HorizontalFlip:
              p: 0.5
          - Normalize:
              mean: ${AUGMENTATIONS.mean}
              std: ${AUGMENTATIONS.std}
          - ToTensorV2:
  VALIDATION:
    - Compose:
        transforms:
          - LongestMaxSize:
              max_size: ${AUGMENTATIONS.crop_size[0]}
          - PadIfNeeded:
              min_height: ${AUGMENTATIONS.crop_size[0]}
              min_width: ${AUGMENTATIONS.crop_size[1]}
              border_mode: 0 #"cv2.BORDER_CONSTANT"
              value: 0
              mask_value: ${DATASET.IGNORE_INDEX}
          - Normalize:
              mean: ${AUGMENTATIONS.mean}
              std: ${AUGMENTATIONS.std}
          - ToTensorV2:
  TEST:
    - Compose:
        transforms:
          - Normalize:
              mean: ${AUGMENTATIONS.mean}
              std: ${AUGMENTATIONS.std}
          - ToTensorV2:
